spring:
  datasource:
    initialization-mode: always
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:quoshelf
    username: quo
    password: quo
    tomcat:
      maxActive: 5
      maxIdle: 5
      minIdle: 5
      initialSize: 5
  h2:
    console:
      enabled: true